<?php

/**
 * @file
 * This is a file.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;
use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_preprocess_HOOK().
 */
function hoeringsportal_data_preprocess_page(&$variables) {
  if ($node = \Drupal::request()->attributes->get('node')) {
    if ('page_map' === $node->bundle()) {
      $value = $node->get('field_map_configuration')->value;
      $helper = \Drupal::getContainer()->get('hoeringsportal_data.map_helper');
      $configuration = $helper->parseConfiguration($value, TRUE);
      $variables['map_configuration'] = $configuration;

      $variables['#attached']['library'][] = 'hoeringsportal_data/septima-widget-api';

      $variables['#cache']['tags'][] = 'node:' . $node->id();
    }
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function hoeringsportal_data_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ('node' === $entity_type->id() && 'page_map' === $bundle && isset($fields['field_map_configuration'])) {
    $fields['field_map_configuration']->addConstraint('MapConfiguration');
  }
}

/**
 * Implements hook_node_presave().
 */
function hoeringsportal_data_node_presave(NodeInterface $node) {
  $helper = \Drupal::service('hoeringsportal_data.map_item_helper');
  $helper->updateData($node);

  $helper = \Drupal::service('hoeringsportal_data.localplan_item_helper');
  $helper->updateData($node);
}

/**
 * Implements hook_user_login().
 */
function hoeringsportal_data_user_login(UserInterface $account) {
  if ($account->hasPermission('access content overview')) {
    $url = Url::fromRoute('system.admin_content')->toString();
    $response = new RedirectResponse($url);
    $response->send();
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function hoeringsportal_data_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  _hoeringsportal_data_translate_element($element, $form_state, $context);
}

/**
 * Implements hook_field_widget_multivalue_form_alter().
 */
function hoeringsportal_data_field_widget_multivalue_form_alter(&$element, FormStateInterface $form_state, $context) {
  _hoeringsportal_data_translate_element($element, $form_state, $context);
}

/**
 * Implements field_group_form_process_build_alter().
 */
function hoeringsportal_data_field_group_form_process_build_alter(array &$element) {
  foreach ($element as $key => &$value) {
    if (preg_match('/^group_/', $key)) {
      _hoeringsportal_data_translate_element($value);
    }
  }
}

/**
 * Translate a form element.
 */
function _hoeringsportal_data_translate_element(&$element, FormStateInterface $form_state = NULL, $context = NULL) {
  foreach (['#title', '#description'] as $key) {
    $field = &$element[$key] ?? NULL;
    if (!empty($field) && !$field instanceof TranslatableMarkup) {
      // phpcs:ignore
      $field = t((string) $field);
      if (isset($element['value'])) {
        _hoeringsportal_data_translate_element($element['value'], $form_state, $context);
      }
    }
  }
}
