<?php

/**
 * @file
 * Module for node access.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\hoeringsportal_content_access\Helper;
use Drupal\node\NodeInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_node_access().
 */
function hoeringsportal_content_access_node_access(NodeInterface $node, string $operation, AccountInterface $account) {
  return _hoeringsportal_content_access_get_helper()->nodeAccess($node, $operation, $account);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form.
 */
function hoeringsportal_content_access_form_node_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  return _hoeringsportal_content_access_get_helper()->nodeFormAlter($form, $form_state, $form_id);
}

/**
 * Implements template_preprocess_form_element().
 */
function hoeringsportal_content_access_preprocess_form_element(&$variables) {
  return _hoeringsportal_content_access_get_helper()->preprocessFormElement($variables);
}

/**
 * Implements hook_views_query_alter().
 */
function hoeringsportal_content_access_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  _hoeringsportal_content_access_get_helper()->viewsQueryAlter($view, $query);
}

/**
 * Get helper.
 */
function _hoeringsportal_content_access_get_helper(): Helper {
  return \Drupal::service(Helper::class);
}
