<?php

/**
 * Implements hook_form_alter().
 */
function hoeringsportal_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if($form_id == 'user_form') {
    $form['#theme'] = 'hoeringsportal_user_form';
    $form['#user_account'] = Drupal::request()->attributes->get('user');
  }
}

/**
 * Implements hook_theme().
 *
 * Use a template for creating the full form.
 */
function hoeringsportal_user_theme($existing, $type, $theme, $path) {
  return array(
    'hoeringsportal_user_form' => array(
      'render element' => 'form',
    ),
  );
}
