<?php

/**
 * @file
 * Contains hoeringsportal_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hoeringsportal_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hoeringsportal_api module.
    case 'help.page.hoeringsportal_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Høringsportal API') . '</p>';
      return $output;

    default:
  }
}
