<?php

/**
 * @file
 * Contains hoeringsportal_hearing.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_help().
 */
function hoeringsportal_hearing_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hoeringsportal_hearing module.
    case 'help.page.hoeringsportal_hearing':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Hearings') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function hoeringsportal_hearing_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ('node_hearing_edit_form' === $form_id && isset($form['field_reply_deadline'])) {
    $node = $form_state->getFormObject()->getEntity();
    if (NULL !== $node->id()) {
      $form['field_reply_deadline']['#suffix'] = Link::fromTextAndUrl(
        t('Add hearing reply'),
        Url::fromRoute(
          'hoeringsportal_deskpro.hearing.ticket_add',
          ['node' => $node->id()],
          ['attributes' => ['class' => ['button']]]
        )
      )->toString();
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view() for node entities.
 */
function hoeringsportal_hearing_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getType() == 'hearing') {
    $view_mode_change_title = [
      'full',
      'hearing_ticket_add',
      'hearing_ticket_view',

    ];
    $content_state = $entity->field_content_state->value;
    if (in_array($view_mode, $view_mode_change_title)) {
      switch ($content_state) {
        case 'upcoming':
          $start_date = $entity->field_start_date->date->getTimestamp()->format_date('hoeringsportal_date');
          $state = ' (' . t('Hearing deadline: @deadline', ['@deadline' => $start_date]) . ')';
          break;

        case 'finished':
          $state = ' (' . t('Hearing deadline has passed') . ')';
          break;

        default:
          $state = '';
      }
      $title = $build['title'][0]['#context']['value'];
      $new_title = $title . $state;
      $build['title'][0]['#context']['value'] = $new_title;
    }

  }
}
