<?php

/**
 * @file
 * Contains hoeringsportal_deskpro.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hoeringsportal_deskpro_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hoeringsportal_deskpro module.
    case 'help.page.hoeringsportal_deskpro':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Deskpro integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function hoeringsportal_deskpro_theme() {
  return [
    'block__hoeringsportal_hearing_ticket' => [
      'variables' => [
        'ticket' => NULL,
        'ticket_messages' => NULL,
        'ticket_attachments' => NULL,
      ],
    ],
  ];
}
