<?php

/**
 * @file
 * This is a file.
 */

use Drupal\Core\Url;
use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_user_login().
 */
function hoeringsportal_misc_user_login(UserInterface $account) {
  if ($account->hasPermission('access content overview')) {
    $url = Url::fromRoute('system.admin_content')->toString();
    $response = new RedirectResponse($url);
    $response->send();
  }
}
