<?php

/**
 * @file
 * Høringsportal forms.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add specific styles for node forms.
 */
function hoeringsportal_forms_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['advanced']['#attributes']['style'] = 'margin-top:1em';

  $form['#attached']['library'][] = 'hoeringsportal_forms/form_styles';
  $form['field_media_image']['widget']['entity_browser']['#weight'] = -10;
  $form['field_media_image']['widget']['current']['#weight'] = -50;

  $form['field_media_document']['widget']['entity_browser']['#weight'] = -10;
  $form['field_media_document']['widget']['current']['#weight'] = -50;
}

/**
 * Implements hook_form_paragraphs_subform_alter().
 *
 * Add form states to landing page.
 */
function hoeringsportal_forms_form_paragraphs_subform_alter(&$element) {
  // Establish that we have radios to act on.
  if (array_key_exists('field_type', $element)) {
    // Use delta to separate states between paragraphs.
    $delta = $element['#parents']['1'];
    // When to show title field.
    $element['field_paragraph_title']['#states'] = array(
      'visible' => array(
        ':input[name="field_section[' . $delta . '][subform][field_type]"]' => array(
          array('value' => 'one_project_two_static'),
          array('value' => 'two_projects'),
          array('value' => 'three_projects')
        ),
      ),
    );
    // When to show Project/Hearing 1 field.
    $element['field_project_hearing_1']['#states'] = array(
      'visible' => array(
        ':input[name="field_section[' . $delta . '][subform][field_type]"]' => array(
          array('value' => 'one_project_two_static'),
          array('value' => 'two_projects'),
          array('value' => 'three_projects')
        ),
      ),
    );
    // When to show Project/Hearing 2 field.
    $element['field_project_hearing_2']['#states'] = array(
      'visible' => array(
        ':input[name="field_section[' . $delta . '][subform][field_type]"]' => array(
          array('value' => 'two_projects'),
          array('value' => 'three_projects')
        ),
      ),
      'disabled' => array(
        ':input[name="field_section[' . $delta . '][subform][field_type]"]' => array(
          array('value' => 'one_project_two_static'),
        ),
      ),
    );
    // When to show Project/Hearing 3 field.
    $element['field_project_hearing_3']['#states'] = array(
      'visible' => array(
        ':input[name="field_section[' . $delta . '][subform][field_type]"]' => array('value' => 'three_projects'),
      ),
      'disabled' => array(
        ':input[name="field_section[' . $delta . '][subform][field_type]"]' => array(
          array('value' => 'one_project_two_static'),
          array('value' => 'two_projects')
        ),
      ),
    );
    // When to show static pages field.
    $element['field_static_pages']['#states'] = array(
      'visible' => array(
        ':input[name="field_section[' . $delta . '][subform][field_type]"]' => array('value' => 'one_project_two_static'),
      ),
      'disabled' => array(
        ':input[name="field_section[' . $delta . '][subform][field_type]"]' => array(
          array('value' => 'two_projects'),
          array('value' => 'three_projects')
        ),
      ),
    );
  }
}
